services:
  - type: web
    name: chatbot-api
    env: python
    buildCommand: ""
    startCommand: uvicorn chatbot_api:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: firebase-adminsdk.json
